### ISSUE TITLE
Activating Style Settings demo and the running cron generates errors:

### ISSUE THREAD

**Issue by vtad** [backdrop-contrib/style_settings#2]
. The specified file temporary://filecVCjxw could not be copied because the destination directory is not properly configured. This may be caused by a problem with file or directory permissions. More information is available in the system log.

. The specified file temporary://file7kTaCg could not be copied because the destination directory is not properly configured. This may be caused by a problem with file or directory permissions. More information is available in the system log.

and afterwards:
Rewritten successfully modules/style_settings-1.x-1.x/demo/css/FOO.css to public://style_settings/f2ba72356448127c03da92331c00f652.FOO.css

**Comment by lolandese** [comment]
I have seen the error message before fixing #1 . Now I am not able to reproduce it anymore. All seems fine. Probably we killed two birds with one stone?

Can you check?

**Comment by lolandese** [comment]
> Probably we killed two birds with one stone?

I assume we did.

**Comment by LeeteqXV** [comment]
I just ran into this very same issue. Both on a 1.7.0 site with close to no additional modules or themes, and after upgrading it to 1.7.1. Same message, and I do not know where I should expect there to be a menu entry for it. Cannot seem to spot it anywhere, although the module is enabled.
Reopen the issue?

**Comment by schoenid** [comment]
@lolandese - Well, installing it with Backdrops module installer `/admin/modules/install` gives the same issue.
The trailing comma is back in the JSON file.

Installing it manually from github brings the correct version, without comma in the JSON file.
